version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python server/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/source

  primary_database:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - primary_database:/var/lib/postgresql/data

volumes:
  primary_database:
    
